[package]
name = "breeze_gui"
version = "1.0.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
libium = { git = "https://github.com/gorilla-devs/libium", version = "1.32.0" }
serde = "1.0.210"
serde_json = "1.0.128"
