[package]
name = "breeze_pack"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
console.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true

uuid = { version = "1.23.1", features = ["v4"] }
sevenz-rust = "0.6.1"
ferinth = "2.13.1"
